### ISSUE TITLE
 Class "cache" does not exist

### ISSUE THREAD

**Issue by jannescb** [litstack/litstack#227]
This line https://github.com/litstack/litstack/blob/0348fe0ec7c3c150c1884a7cd4e9cd544a02289e/src/Crud/CrudServiceProvider.php#L324 seems to break something:
 
<img width="784" alt="Bildschirmfoto 2021-07-19 um 14 40 31" src="https://user-images.githubusercontent.com/17292622/126161353-f9f7ce7d-f94c-4e8e-819f-9143e57886c5.png">

Just happened in several apps after updating to 3.7.7

**Comment by lpheller** [comment]
This seems to be an issue with packages registering fields, rather than Litstack core itself. 

Some packages, like .e.g [litstack/wikipedia-field](https://github.com/litstack/wikipedia-field) used the `register` method to provide new fields using `Form::field`.
This worked as long as the Form didn't had to resolve any dependencies. With the latest update to `3.7.7` which added the Cache as a dependency, those packages need to be updated to wait for the application to be fully booted.
