### ISSUE TITLE
Customize favicon / logo

### ISSUE THREAD

**Issue by astroop** [litstack/litstack#74]
Is there a way to customize favicon or the topbar logo ? It will be useful when using litstack for differents projects.

I found this line in the resources/views/partials/topbar but how to uncomment it without editing the vendor folder

`<img src="{{ route('lit.logo') }}" class="img-fluid" alt="">`

**Comment by cbl** [comment]
Hi @astroop 

Please note, that we are highly not recommending on overriding views since we might change them at any time.

Here's the solution if you want to do it anyway:

According to [Laravel's documentation](https://laravel.com/docs/8.x/packages#views) you may override views by creating a folder in `resources/views/vendor` that has the name of the namespace you want to override. In your case it would be `litstack`. So if you want to override the logo you may create the file `resources/views/vendor/litstack/partials/topbar/topbar.blade.php` with the following content:

```php
<nav class="lit-topbar justify-content-between align-items-center">
    <div>
        <a href="{{lit()->url('/')}}" class="lit-brand">
            My Custom Logo
        </a>
    </div>
    <div>
        <div class="lit-hide" id="lit-topbar-right">
        
            @auth('lit')
                @include('litstack::partials.topbar.navigation')
            @endauth
            
        </div>
    </div>
</nav>
```

**Comment by astroop** [comment]
I understand it's not recommended to overwrite the litstacks templates, i think i'll have to find another solution :grin:  .

Thanks for your answer !

**Comment by lhoucinecherif** [comment]
Hi, 
You can customize the favicon without overwriting the litstack templates by using the RouteServiceProvider : 
in your ./lit/app/Providers/RouteServiceProvider.php you can change the favicon or logo routes like this : 

```
 public function map()
    {
        $this->mapWebRoutes();

        // Change the Logo
        Route::get('images/lit-logo.png', function(){return response()->file(public_path('img/logo-dark--sm.png'));})->name('logo');

        // Change the Favicon.
        Route::get('favicon/favicon-32x32.png', function(){return response()->file(public_path('favicon/favicon-32x32.png'));})->name('favicon-big');
        Route::get('favicon/favicon-16x16.png', function(){return response()->file(public_path('favicon/favicon-16x16.png'));})->name('favicon-small');

    }
```
assuming you have a favicons named "favicon-32x32.png" and "favicon-16x16.png" in ./public/favicon folder,  and a logo named logo-dark--sm.png  in ./public/img/ folder.
